name: EnderBow
version: 1.0.0
author: flizz (Jan Sadownik)
main: live.jansadownik.enderbow.EnderBow

commands:
  enderbow:
    description: Gives enderbow
    permission: enderbow.command.enderbow
    usage: /<command> [player]

permissions:
  enderbow.*:
    description: Gives all permissions
    children:
      enderbow.command.enderbow: true
      enderbow.use.enderbow: true
      enderbow.bypass.use.enderpearl: true
  enderbow.command.enderbow:
    description: Lets you use /enderbow command
    default: op
  enderbow.use.enderbow:
    description: Lets you use enderbow item
    default: true
  enderbow.bypass.use.enderpearl:
    description: Lets you bypass obligation to have enderpearl
    default: op